name: poc_html_editor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.17
  flutter_switch: ^0.3.2
  hyperion_components:
    git:
      url: 'https://github.com/dpep-cgs/shared_flutter_hyperion_components'
      ref: 'main'
  html_editor_enhanced: ^2.5.1
  html2md: ^1.3.1
  font_inspire_twdc:
    git:
      url: https://github.com/dpep-cgs/shared_flutter_font_inspire_twdc
      ref: main
  markdown: ^7.1.1
  markdown_widgets:
    git:
      url: 'https://github.com/dpep-cgs/shared_flutter_markdown'
      ref: 'main'
  pointer_interceptor: ^0.9.3+4
  url_launcher: ^6.1.12
  validation:
    git:
      url: 'https://github.com/dpep-cgs/shared_dart_validation'
      ref: 'main'
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
